// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.MathCalculator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("result")]
        public long Result { get; set; }

        [JsonProperty("operation")]
        public string Operation { get; set; }

        [JsonProperty("input")]
        public Input Input { get; set; }

        [JsonProperty("steps")]
        public string[] Steps { get; set; }
    }

    public partial class Input
    {
        [JsonProperty("a")]
        public long A { get; set; }

        [JsonProperty("b")]
        public long B { get; set; }
    }
}
